version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      # functions配下のnpm設定
      - restore_cache:
          key: dependency-cache-{{ checksum "functions/yarn.lock" }}
      - run:
          name: Install functions
          command: yarn
          working_directory: functions
      - save_cache:
          key: dependency-cache-{{ checksum "functions/package-lock.json" }}
          paths:
            - functions/node_modules
      # トップレベルのnpm設定
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Set Firebase Config
          command: npm run set-config
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  deploy_master:
    jobs:
      - build:
          filters:
            branches:
              only: master
